"""
Auto-generate a structured plain-text research note from signal output.
"""

import logging
from datetime import datetime
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)


def _fmt(val, decimals: int = 2) -> str:
    if pd.isna(val):
        return "N/A"
    return f"{val:+.{decimals}f}" if isinstance(val, float) else str(val)


def generate_report(
    signals_df: pd.DataFrame,
    features_df: pd.DataFrame,
    report_dir: str = "output",
) -> str:
    """
    Build a human-readable research note from the latest signals.

    Returns the report text and saves it to *report_dir*.
    """
    latest = signals_df.iloc[-1]
    today = latest.name if hasattr(latest.name, "strftime") else datetime.now()
    date_str = today.strftime("%B %d, %Y")

    yc = latest.get("yield_curve_spread")
    cs = latest.get("credit_spread")
    vol = latest.get("volatility")
    mom30 = latest.get("momentum_30d")
    mom90 = latest.get("momentum_90d")
    regime = latest.get("regime", "N/A")
    score = latest.get("risk_score")

    yc_streak = _inversion_streak(signals_df)

    lines = [
        "=" * 64,
        "  FIXED INCOME SIGNAL ENGINE — RESEARCH NOTE",
        "=" * 64,
        f"  Date: {date_str}",
        f"  Regime: {regime}",
        f"  Composite Risk Score: {_fmt(score)}",
        "-" * 64,
        "",
        "MARKET SNAPSHOT",
        f"  Yield Curve Spread (10Y-2Y):  {_fmt(yc)} %",
        f"  Credit Spread (HY OAS):       {_fmt(cs)} %",
        f"  30-Day Bond Momentum:         {_fmt(mom30)} %",
        f"  90-Day Bond Momentum:         {_fmt(mom90)} %",
        f"  Annualised Volatility:        {_fmt(vol)} %",
        "",
        "-" * 64,
        "SIGNAL INTERPRETATION",
        "",
    ]

    if yc is not None and yc < 0:
        lines.append(
            f"  * Yield curve has been inverted for {yc_streak} consecutive "
            f"trading day(s), a historically reliable recession leading indicator."
        )
    elif yc is not None and yc < 0.25:
        lines.append(
            "  * Yield curve is near-flat, signalling uncertainty about the "
            "growth outlook."
        )
    else:
        lines.append(
            "  * Yield curve is positively sloped, consistent with a normal "
            "growth environment."
        )

    if cs is not None and cs > 5:
        lines.append(
            f"  * Credit spreads are elevated at {_fmt(cs)}%, indicating "
            "stress in corporate credit markets."
        )
    elif cs is not None and cs > 3.5:
        lines.append(
            "  * Credit spreads are moderately wide; market pricing reflects "
            "caution but not outright stress."
        )
    else:
        lines.append(
            "  * Credit spreads are tight, consistent with risk-on sentiment."
        )

    if mom30 is not None and mom30 < 0:
        lines.append(
            "  * Short-term bond momentum is negative, suggesting recent selling "
            "pressure in rates markets."
        )
    else:
        lines.append(
            "  * Short-term bond momentum is positive, indicating a flight-to-"
            "quality or rate-cut expectations."
        )

    lines += [
        "",
        "-" * 64,
        "RISK ASSESSMENT",
        "",
        f"  Current regime classification: {regime}",
        "",
    ]

    if regime == "Recession Risk":
        lines.append(
            "  The combination of an inverted yield curve and weakening momentum "
            "historically precedes economic downturns. Defensive positioning "
            "in fixed income may be warranted."
        )
    elif regime == "Credit Stress":
        lines.append(
            "  Elevated credit spreads signal deteriorating risk appetite. "
            "Consider reducing high-yield exposure in favour of investment-grade "
            "or sovereign bonds."
        )
    elif regime == "Risk On":
        lines.append(
            "  Markets are pricing in benign conditions. Carry strategies and "
            "spread compression trades may offer value, but monitor for "
            "complacency."
        )
    else:
        lines.append(
            "  Mixed signals across indicators. No strong directional conviction; "
            "maintain balanced fixed income positioning."
        )

    lines += [
        "",
        "=" * 64,
        "  Generated by Fixed Income Signal Engine",
        "=" * 64,
    ]

    report_text = "\n".join(lines)

    out_dir = Path(report_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    file_path = out_dir / f"report_{today.strftime('%Y-%m-%d')}.txt"
    file_path.write_text(report_text, encoding="utf-8")
    logger.info("Report saved to %s", file_path)

    return report_text


def _inversion_streak(signals_df: pd.DataFrame) -> int:
    """Count consecutive days (from the end) where yield curve < 0."""
    spreads = signals_df["yield_curve_spread"]
    streak = 0
    for val in reversed(spreads.values):
        if val < 0:
            streak += 1
        else:
            break
    return streak
